[package]
name = "snake"
version = "0.1.0"
edition = "2021"
# https://github.com/not-fl3/macroquad/blob/master/examples/snake.rs
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3"